name: dabka
description: "A Flutter/Firebase application for weddings"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  icons_plus: ^5.0.0
  flutter_animate: ^4.5.0
  hive: ^2.2.3
  toastification: ^2.0.0
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  path_provider: ^2.1.3
  animated_custom_dropdown: ^3.0.0
  shadow_overlay: ^1.0.5
  intl_phone_number_field: ^0.1.9
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.2.6
  data_table_2: ^2.5.12
  date_format: ^2.0.7
  animated_line_through: ^1.0.4
  image_cropper: ^6.0.0
  image_picker: ^1.1.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  cached_network_image: ^3.3.1
  flutter_image_stack: ^0.0.7
  multi_image_picker_view: ^1.0.2
  video_player: ^2.8.6
  uuid: ^4.4.0
  flutter_rating_bar: ^4.0.1
  scrolling_text: ^0.0.4
  another_xlider: ^3.0.2
  animated_toggle_switch: ^0.8.2
  async: ^2.11.0
  pie_chart: ^5.4.0
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
    - assets/images/
    - assets/icons/
    - assets/jsons/
